kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.helper.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.helper.name }}
roleRef:
  kind: Role
  name: {{ .Values.helper.name }}
  apiGroup: ""