---
dependency:
  name: galaxy
driver:
  name: docker
lint: |   
  set -e
  yamllint .
platforms:
  - name: debian-bullseye
    image: "ghcr.io/hspaans/molecule-container-debian:bullseye"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
