{
 "title": "Cointracker",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Container MEM current usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"cointracker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bot uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{name=\"cointracker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bot /start requests 24h",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "increase(requests_total[24h])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bot /start requests 7d",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "increase(requests_total[7d])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bot /start requests since last start",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CoinmarketcapAPI Requests Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(request_time_seconds_bucket[$__rate_interval])))",
     "legendFormat": "99% requests"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(request_time_seconds_bucket[$__rate_interval])))",
     "legendFormat": "95% requests"
    },
    {
     "expr": "histogram_quantile(0.80, sum by(le) (rate(request_time_seconds_bucket[$__rate_interval])))",
     "legendFormat": "80% requests"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(request_time_seconds_bucket[$__rate_interval])))",
     "legendFormat": "50% requests"
    }
   ]
  },
  {
   "title": "Bot /start requests total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(requests_total[10y])) * 86400",
     "legendFormat": "/start requests"
    }
   ]
  }
 ]
}