---
- hosts: cointracker
  gather_facts: false
  vars:
    registry_url: 381171443050.dkr.ecr.us-east-2.amazonaws.com
    registry_region: us-east-2
    image_name: cointracker
    image_tag: latest
  tasks:
    - name: AWS ECR get Docker token and login
      shell: |
        docker login --username AWS --password $(aws ecr get-login-password --region {{ registry_region }}) \
        {{ registry_url }}
      register: ecr_token

    - name: Pull Docker image
      tags: docker_pull
      community.docker.docker_image:
        name: "{{ registry_url }}/{{ image_name }}:{{ image_tag}}"
        source: pull

    - name: Ensure config dir exists
      tags: config_template
      ansible.builtin.file:
        path: "{{ cointracker_config_dir }}"
        state: directory

    - name: Touch config file
      tags: config_template
      ansible.builtin.file:
        path: "{{ cointracker_config_path }}"
        state: touch

    - name: Template config file
      tags: config_template
      ansible.builtin.template:
        src: config.yml.j2
        dest: "{{ cointracker_config_path }}"

    - name: Restart docker container
      tags: docker_restart
      community.docker.docker_container:
        name: myapplication
        image: "{{ registry_url }}/{{ image_name }}:{{ image_tag}}"
        state: started
        restart_policy: always
        network_mode: host
        recreate: yes
        volumes:
          - /opt/cointracker:/etc/cointracker
          - /var/log/cointracker:/application/tracker/logs

