- hosts: all
  become: yes
  vars:
    base_packages:
      - net-tools
      - apt-transport-https 
      - ca-certificates 
      - curl
    k8s_packages:
      - kubelet
      - kubeadm
      - kubectl
  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ tags.Name }}"

    - name:
      shell: |
        apt-get update
    
    - name: Install base packages
      apt:
        pkg: "{{ base_packages }}"
        update_cache: yes

    - import_role:
        name: container
      vars:
        containerd_config_cgroup_driver_systemd: yes

    - name: Download the Google Cloud public signing key
      shell: |
        curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
      
    - name: Add the Kubernetes apt repository
      shell: |
        echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

    - name: Install k8s packages
      apt:
        pkg: "{{ k8s_packages }}"
        update_cache: yes
      
    - name: Prevent k8s packages from being upgraded
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop: "{{ k8s_packages }}"

    - name: Disable swap
      shell: |
        swapoff -a && sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    - name: Load kernel modules
      shell: |
        tee /etc/modules-load.d/containerd.conf <<EOF
        overlay
        br_netfilter
        EOF
        
        modprobe overlay
        modprobe br_netfilter

    - name: Set kernel params
      shell: |
        tee /etc/sysctl.d/kubernetes.conf <<EOF
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
        net.ipv4.ip_forward = 1
        EOF 
    
    - name: Reload changes
      shell: |
        sysctl --system


# kubeadm init --control-plane-endpoint k8s-controller.mrf0str-private.com --pod-network-cidr 10.32.0.0/12
# kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml

