# config cron job
# 0 0 * * * python3 /home/ubuntu/dump_redis.py

---
- name: Redis backup job
  hosts: redis
  tasks:
  - name: Ensure python packages present
    ansible.builtin.pip:
      name: "{{ item }}"
    loop: "{{ redis_host_python_packages }}"

  - name: Create directory 
    file:
      path: "{{ redis_backup_dir_name }}"
      state: directory

  - name: Copy backup script
    copy:
      src: "{{ redis_backup_script.name }}"
      dest: "{{ redis_backup_dir_name }}"

  - name: Download python file from internet to remote machine
    get_url:
      url: "{{ redis_backup_lib_url }}"
      dest: "{{ redis_backup_dir_name }}"

  - name: Create cron job
    cron:
      name: "{{ redis_backup_cron_name }}"
      job: "python3 {{ redis_backup_dir_name }}/{{ redis_backup_script.name }} {{ redis_backup_script.args }}"
      minute: 0
      hour: 0

  - name: Create a symbolic link for log file
    ansible.builtin.file:
      src: "{{ redis_backup_dir_name }}/{{ redis_backup_logfile_name }}"
      dest: "/var/log/{{ redis_backup_logfile_name }}"
      state: link
      force: yes

  - name: Test if cron job is working
    shell: "crontab -l | grep {{ redis_backup_cron_name }}"
